all:
  children:
    nat:
      hosts:
        hydrogen.nat.cory.red:
        helium.nat.cory.red:
        lithium.nat.cory.red:
        beryllium.nat.cory.red:
        boron.nat.cory.red:
    vpses:
      children:
        ovh:
          hosts:
            prod.cory.red:
            dev.cory.red:
            mx.cory.red:
    dedicated:
      children:
        hetzner:
          hosts:
            the.cory.red:
    dankbotlist:
       children:
         appserver:
           hosts:
             prod.cory.red:
             dev.cory.red:
         dbserver:
           hosts:
             the.cory.red:

